apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: orders
spec:
  template:
    spec:
      containers:
      - name: orders
        env:
        - name: SPRING_DATASOURCE_WRITER_URL
          valueFrom:
            configMapKeyRef:
              name: orders-db
              key: endpoint
        - name: SPRING_DATASOURCE_WRITER_USERNAME
          valueFrom:
            secretKeyRef:
              name: orders-db
              key: username
        - name: SPRING_DATASOURCE_WRITER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-db
              key: password
        - name: SPRING_DATASOURCE_READER_URL
          valueFrom:
            configMapKeyRef:
              name: orders-db
              key: endpoint
        - name: SPRING_DATASOURCE_READER_USERNAME
          valueFrom:
            secretKeyRef:
              name: orders-db
              key: username
        - name: SPRING_DATASOURCE_READER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-db
              key: password
        - name: SPRING_RABBITMQ_ADDRESSES
          valueFrom:
            configMapKeyRef:
              name: orders-mq
              key: endpoint
        - name: SPRING_RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: orders-mq
              key: username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-mq
              key: password
