apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: orders
spec:
  template:
    spec:
      containers:
      - name: orders
        env:
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq.rabbitmq.svc
