apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: checkout
spec:
  template:
    spec:
      containers:
      - name: checkout
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: checkout-redis
              key: endpoint
