apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: checkout
spec:
  template:
    spec:
      containers:
      - name: checkout
        env:
        - name: REDIS_URL
          value: redis://checkout-redis:6379
