apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: default
  namespace: opentelemetry
spec:
  image: public.ecr.aws/aws-observability/aws-otel-collector:v0.21.0
  mode: deployment
  serviceAccount: opentelemetry-collector
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            
    exporters:
      awsxray:

    extensions:
      awsproxy:

    service:
      extensions: [awsproxy]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [awsxray]
